name = input('What is your name? ')
print("Hello, " + name + "!")
name_length = len(name)
name = name.upper()
print("Hello, " + name + "!")
print("Your name is " + str(name_length) + " characters long!")
